/**
 * Cambridge Business 9609 — starter deck.
 *
 * Authored for Atlas: standard business formulae, definitions and exam-technique
 * rules written in our own words. Nothing here is copied from a textbook, a past
 * paper, or a mark scheme — those arrive through the ingestion pipeline as the
 * learner's own private material (MASTER-PROMPT.md §7).
 *
 * Every item states the assessment objectives it exercises, because the whole point
 * of the plan is to spend time where the marks are.
 */

import type { Item } from '../schema';

type Draft = Omit<Item, 'provenance' | 'licence' | 'difficulty' | 'tags'> &
  Partial<Pick<Item, 'difficulty' | 'tags'>>;

const authored = (drafts: Draft[]): Item[] =>
  drafts.map((d) => ({
    difficulty: 0,
    tags: [],
    ...d,
    provenance: 'authored' as const,
    licence: 'authored-atlas' as const,
  }));

/** Formula cards: the free AO1/AO2 marks. Recall must be automatic. */
const formulas = authored([
  {
    id: '9609-f-contribution',
    objectiveId: 's5.5.3',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Contribution per unit =',
    answer: 'selling price per unit − variable cost per unit',
    working: 'Contribution is what each unit leaves behind to pay fixed costs, and then to make profit.',
    tags: ['formula', 'break-even'],
  },
  {
    id: '9609-f-breakeven',
    objectiveId: 's5.5.3',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Break-even output =',
    answer: 'fixed costs ÷ contribution per unit',
    working: 'Units needed before contribution has covered every fixed cost.',
    tags: ['formula', 'break-even'],
  },
  {
    id: '9609-f-margin-safety',
    objectiveId: 's5.5.3',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Margin of safety =',
    answer: 'current (or budgeted) output − break-even output',
    working: 'How far sales can fall before the business starts making a loss.',
    tags: ['formula', 'break-even'],
  },
  {
    id: '9609-f-gross-margin',
    objectiveId: 's5.5.6',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Gross profit margin =',
    answer: '(gross profit ÷ revenue) × 100',
    tags: ['formula', 'ratio'],
  },
  {
    id: '9609-f-operating-margin',
    objectiveId: 's5.5.6',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Operating profit margin =',
    answer: '(operating profit ÷ revenue) × 100',
    tags: ['formula', 'ratio'],
  },
  {
    id: '9609-f-roce',
    objectiveId: 's10.10.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Return on capital employed (ROCE) =',
    answer: '(operating profit ÷ capital employed) × 100',
    working: 'Capital employed = total equity + non-current liabilities. ROCE is the headline profitability ratio: return earned on all long-term funds.',
    tags: ['formula', 'ratio'],
    difficulty: 0.5,
  },
  {
    id: '9609-f-current-ratio',
    objectiveId: 's10.10.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Current ratio =',
    answer: 'current assets ÷ current liabilities',
    tags: ['formula', 'ratio', 'liquidity'],
  },
  {
    id: '9609-f-acid-test',
    objectiveId: 's10.10.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Acid-test (quick) ratio =',
    answer: '(current assets − inventory) ÷ current liabilities',
    working: 'Inventory is stripped out because it is the current asset least reliably turned into cash quickly.',
    tags: ['formula', 'ratio', 'liquidity'],
  },
  {
    id: '9609-f-gearing',
    objectiveId: 's10.10.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Gearing ratio =',
    answer: '(non-current liabilities ÷ capital employed) × 100',
    working: 'The share of long-term funding that comes from debt rather than equity.',
    tags: ['formula', 'ratio'],
    difficulty: 0.5,
  },
  {
    id: '9609-f-inventory-turnover',
    objectiveId: 's10.10.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Inventory turnover =',
    answer: 'cost of sales ÷ average inventory',
    working: 'Times per period the business sells and replaces its stock. Higher is usually better — unless it signals stock-outs.',
    tags: ['formula', 'ratio', 'efficiency'],
  },
  {
    id: '9609-f-receivable-days',
    objectiveId: 's10.10.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Trade receivable days =',
    answer: '(trade receivables ÷ revenue) × 365',
    working: 'Average days customers take to pay. Rising days is an early cash-flow warning.',
    tags: ['formula', 'ratio', 'efficiency'],
    difficulty: 0.5,
  },
  {
    id: '9609-f-eps',
    objectiveId: 's10.10.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Earnings per share (EPS) =',
    answer: 'profit after tax ÷ number of issued ordinary shares',
    tags: ['formula', 'ratio', 'investor'],
  },
  {
    id: '9609-f-dividend-yield',
    objectiveId: 's10.10.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Dividend yield =',
    answer: '(dividend per share ÷ current market price per share) × 100',
    tags: ['formula', 'ratio', 'investor'],
  },
  {
    id: '9609-f-dividend-cover',
    objectiveId: 's10.10.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Dividend cover =',
    answer: 'earnings per share ÷ dividend per share',
    working: 'How many times the dividend could have been paid out of this year’s earnings. Below 1 means the business is paying out of reserves.',
    tags: ['formula', 'ratio', 'investor'],
    difficulty: 1,
  },
  {
    id: '9609-f-arr',
    objectiveId: 's10.10.2',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Average rate of return (ARR) =',
    answer: '(average annual profit ÷ initial capital cost) × 100',
    working: 'Average annual profit = (total net returns − initial cost) ÷ number of years.',
    tags: ['formula', 'investment-appraisal'],
    difficulty: 1,
  },
  {
    id: '9609-f-payback',
    objectiveId: 's10.10.2',
    type: 'formula',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'How is a payback period with an incomplete final year calculated?',
    answer:
      'Full years until cumulative cash flow is still negative, plus (amount still to be repaid ÷ cash flow in the next year) × 12 months',
    tags: ['formula', 'investment-appraisal'],
    difficulty: 1,
  },
  {
    id: '9609-f-npv',
    objectiveId: 's10.10.2',
    type: 'formula',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'Net present value (NPV) =',
    answer: 'sum of all discounted future net cash inflows − initial cost',
    working:
      'Each year’s cash flow is multiplied by its discount factor first. A positive NPV means the project beats the discount rate used.',
    tags: ['formula', 'investment-appraisal'],
    difficulty: 1,
  },
  {
    id: '9609-f-ped',
    objectiveId: 's8.8.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Price elasticity of demand (PED) =',
    answer: '% change in quantity demanded ÷ % change in price',
    working: 'Normally negative. |PED| > 1 elastic, < 1 inelastic. Ignore the sign only when the question asks for magnitude.',
    tags: ['formula', 'elasticity'],
    difficulty: 0.5,
  },
  {
    id: '9609-f-yed',
    objectiveId: 's8.8.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Income elasticity of demand (YED) =',
    answer: '% change in quantity demanded ÷ % change in real income',
    working: 'Positive for normal goods, negative for inferior goods, above +1 for luxuries.',
    tags: ['formula', 'elasticity'],
  },
  {
    id: '9609-f-capacity',
    objectiveId: 's4.4.3',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Capacity utilisation =',
    answer: '(actual output ÷ maximum possible output) × 100',
    tags: ['formula', 'operations'],
  },
  {
    id: '9609-f-labour-productivity',
    objectiveId: 's2.2.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Labour productivity =',
    answer: 'total output in a period ÷ number of employees',
    tags: ['formula', 'hrm'],
  },
  {
    id: '9609-f-labour-turnover',
    objectiveId: 's2.2.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Labour turnover =',
    answer: '(number of employees leaving in a period ÷ average number employed) × 100',
    tags: ['formula', 'hrm'],
  },
  {
    id: '9609-f-added-value',
    objectiveId: 's1.1.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Added value =',
    answer: 'sales revenue − cost of bought-in materials and components',
    working: 'Not the same as profit: added value still has to cover wages, rent and every other internal cost.',
    tags: ['formula'],
  },
  {
    id: '9609-f-market-share',
    objectiveId: 's3.3.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Market share =',
    answer: '(sales of one business ÷ total sales in the market) × 100',
    tags: ['formula', 'marketing'],
  },
  {
    id: '9609-f-market-growth',
    objectiveId: 's3.3.1',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Market growth =',
    answer: '(change in market size ÷ original market size) × 100',
    tags: ['formula', 'marketing'],
  },
  {
    id: '9609-f-working-capital',
    objectiveId: 's5.5.5',
    type: 'formula',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Working capital =',
    answer: 'current assets − current liabilities',
    tags: ['formula', 'finance'],
  },
  {
    id: '9609-f-float',
    objectiveId: 's9.9.3',
    type: 'formula',
    bloom: 'understand',
    aos: ['AO1', 'AO3'],
    prompt: 'In critical path analysis, total float on an activity =',
    answer: 'latest finish time − earliest start time − activity duration',
    working: 'Activities on the critical path have zero float; delaying them delays the whole project.',
    tags: ['formula', 'cpa'],
    difficulty: 1.5,
  },
]);

/** Definition cards. One idea each — the minimum-information principle. */
const definitions = authored([
  {
    id: '9609-d-opportunity-cost',
    objectiveId: 's1.1.1',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'Opportunity cost',
    answer: 'The benefit of the next best alternative given up when a choice is made.',
    tags: ['definition'],
  },
  {
    id: '9609-d-limited-liability',
    objectiveId: 's1.1.2',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'Limited liability',
    answer:
      'Shareholders can lose no more than the amount they invested; the company’s debts are the company’s, not theirs personally.',
    tags: ['definition'],
  },
  {
    id: '9609-d-stakeholder',
    objectiveId: 's1.1.5',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'Stakeholder',
    answer: 'Any individual or group with an interest in, or affected by, the activities of a business.',
    tags: ['definition'],
  },
  {
    id: '9609-d-smart',
    objectiveId: 's1.1.4',
    type: 'definition',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'What does a SMART objective require?',
    answer: 'Specific, Measurable, Achievable, Realistic (or Relevant) and Time-bound.',
    tags: ['definition', 'framework'],
  },
  {
    id: '9609-d-usp',
    objectiveId: 's3.3.3',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'Unique selling point (USP)',
    answer:
      'The feature of a product that customers see as clearly different from, and better than, competing products.',
    tags: ['definition'],
  },
  {
    id: '9609-d-jit',
    objectiveId: 's9.9.2',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'Just-in-time (JIT) inventory',
    answer:
      'Ordering and producing so that materials arrive exactly when needed, holding almost no buffer stock.',
    working: 'Cuts holding costs and frees working capital, but leaves no cushion against supply disruption.',
    tags: ['definition', 'operations'],
  },
  {
    id: '9609-d-kaizen',
    objectiveId: 's9.9.2',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'Kaizen',
    answer: 'Continuous improvement through many small changes suggested by the workers doing the job.',
    tags: ['definition', 'operations'],
  },
  {
    id: '9609-d-delayering',
    objectiveId: 's7.7.1',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'Delayering',
    answer:
      'Removing one or more levels of hierarchy from an organisational structure, widening the span of control.',
    tags: ['definition', 'structure'],
  },
  {
    id: '9609-d-span-of-control',
    objectiveId: 's7.7.1',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'Span of control',
    answer: 'The number of subordinates who report directly to one manager.',
    tags: ['definition', 'structure'],
  },
  {
    id: '9609-d-organic-growth',
    objectiveId: 's1.1.3',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'Organic growth',
    answer:
      'Growth generated by expanding the firm’s own operations — more outlets, more output, more products — rather than by merger or takeover.',
    tags: ['definition'],
  },
  {
    id: '9609-d-cash-vs-profit',
    objectiveId: 's5.5.5',
    type: 'short-answer',
    bloom: 'understand',
    aos: ['AO1', 'AO3'],
    prompt: 'Why can a profitable business still run out of cash?',
    answer:
      'Profit is recorded when a sale is made, cash when it is received. Long credit terms, rising inventory, or heavy capital spending can drain cash while the income statement still shows a profit.',
    tags: ['definition', 'finance', 'high-value'],
    difficulty: 1,
  },
  {
    id: '9609-d-window-dressing',
    objectiveId: 's10.10.1',
    type: 'short-answer',
    bloom: 'analyse',
    aos: ['AO3', 'AO4'],
    prompt: 'Give one limitation of judging a business on published ratios alone.',
    answer:
      'Published accounts are historic and can be window-dressed; ratios ignore qualitative factors such as staff morale, brand strength and management quality, and mean little without an industry or trend comparison.',
    tags: ['evaluation', 'ratio'],
    difficulty: 1.5,
  },
]);

/** Frameworks that must be on instant recall — they are the scaffolding for AO3. */
const frameworks = authored([
  {
    id: '9609-fw-ansoff',
    objectiveId: 's6.6.2',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1', 'AO2'],
    prompt: 'The four cells of the Ansoff matrix',
    answer:
      'Market penetration (existing product, existing market), product development (new product, existing market), market development (existing product, new market), diversification (new product, new market).',
    working: 'Risk rises as you move away from the existing/existing cell; diversification is the riskiest.',
    tags: ['framework', 'strategy'],
    difficulty: 0.5,
  },
  {
    id: '9609-fw-porter-five',
    objectiveId: 's6.6.2',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1', 'AO2'],
    prompt: 'Porter’s five forces',
    answer:
      'Rivalry among existing competitors, threat of new entrants, threat of substitutes, bargaining power of buyers, bargaining power of suppliers.',
    tags: ['framework', 'strategy'],
    difficulty: 0.5,
  },
  {
    id: '9609-fw-porter-generic',
    objectiveId: 's6.6.2',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1', 'AO2'],
    prompt: 'Porter’s generic strategies',
    answer:
      'Cost leadership, differentiation, and focus (cost focus or differentiation focus) on a narrow segment.',
    working: 'Porter’s warning: a firm that commits to none of them is "stuck in the middle".',
    tags: ['framework', 'strategy'],
  },
  {
    id: '9609-fw-bcg',
    objectiveId: 's8.8.4',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1', 'AO2'],
    prompt: 'The four Boston (BCG) matrix categories',
    answer:
      'Stars (high share, high growth), cash cows (high share, low growth), question marks / problem children (low share, high growth), dogs (low share, low growth).',
    tags: ['framework', 'marketing'],
  },
  {
    id: '9609-fw-herzberg',
    objectiveId: 's2.2.2',
    type: 'short-answer',
    bloom: 'understand',
    aos: ['AO1', 'AO3'],
    prompt: 'What is the central claim of Herzberg’s two-factor theory?',
    answer:
      'Hygiene factors (pay, conditions, supervision) only prevent dissatisfaction; motivation comes separately from motivators such as achievement, recognition, responsibility and advancement.',
    working:
      'The exam-useful consequence: raising pay removes a complaint but does not, on Herzberg’s account, motivate.',
    tags: ['framework', 'motivation', 'high-value'],
    difficulty: 1,
  },
  {
    id: '9609-fw-maslow',
    objectiveId: 's2.2.2',
    type: 'definition',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Maslow’s hierarchy, lowest to highest',
    answer: 'Physiological, safety, social (love/belonging), esteem, self-actualisation.',
    working: 'A level must be broadly satisfied before the next one motivates.',
    tags: ['framework', 'motivation'],
  },
  {
    id: '9609-fw-mcgregor',
    objectiveId: 's2.2.3',
    type: 'definition',
    bloom: 'understand',
    aos: ['AO1', 'AO2'],
    prompt: 'McGregor’s Theory X and Theory Y',
    answer:
      'Theory X assumes workers dislike work and need control; Theory Y assumes they seek responsibility and are self-motivated. The assumption a manager holds shapes the leadership style they use.',
    tags: ['framework', 'leadership'],
  },
  {
    id: '9609-fw-pestle',
    objectiveId: 's6.6.1',
    type: 'definition',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'PESTLE stands for',
    answer: 'Political, Economic, Social, Technological, Legal, Environmental.',
    tags: ['framework', 'external'],
  },
]);

/** Exam technique. On this syllabus, technique is worth more marks than content. */
const technique = authored([
  {
    id: '9609-t-ao-split',
    objectiveId: 's6.6.2',
    type: 'short-answer',
    bloom: 'remember',
    aos: ['AO1'],
    prompt: 'Across the whole A Level, how are the 200 raw marks split between AO1, AO2, AO3 and AO4?',
    answer: 'Exactly 50 marks each — knowledge is only a quarter of the qualification.',
    working:
      'This is the single most useful number on the course: revision that is only memorisation is competing for 25% of the marks.',
    tags: ['exam-technique', 'high-value'],
    difficulty: 1,
  },
  {
    id: '9609-t-command-state',
    objectiveId: 's6.6.2',
    type: 'short-answer',
    bloom: 'understand',
    aos: ['AO1'],
    prompt: 'What is the highest assessment objective a "state" or "identify" question can reward?',
    answer: 'AO1 only. No marks for development, so writing more earns nothing.',
    tags: ['command-word', 'exam-technique'],
  },
  {
    id: '9609-t-command-analyse',
    objectiveId: 's6.6.2',
    type: 'short-answer',
    bloom: 'understand',
    aos: ['AO3'],
    prompt: 'What does "analyse" require that "explain" does not?',
    answer:
      'A developed chain of consequences — cause → effect → effect on the business — not just a reason stated and defined.',
    tags: ['command-word', 'exam-technique'],
    difficulty: 1,
  },
  {
    id: '9609-t-command-evaluate',
    objectiveId: 's6.6.2',
    type: 'short-answer',
    bloom: 'evaluate',
    aos: ['AO4'],
    prompt: 'What must an answer contain to access AO4 on "evaluate", "discuss", "recommend" or "to what extent"?',
    answer:
      'A supported judgement: weigh the arguments, decide, and justify the decision against the specific business in the case — not a summary of both sides.',
    tags: ['command-word', 'exam-technique', 'high-value'],
    difficulty: 1.5,
  },
  {
    id: '9609-t-application',
    objectiveId: 's6.6.2',
    type: 'short-answer',
    bloom: 'apply',
    aos: ['AO2'],
    prompt: 'What is the cheapest way to lose AO2 marks in a case-study answer?',
    answer:
      'Writing a generic answer that would fit any business. AO2 needs the case’s own facts — its name, numbers, market and constraints — woven into the argument.',
    tags: ['exam-technique', 'high-value'],
    difficulty: 1,
  },
  {
    id: '9609-t-conclusion',
    objectiveId: 's6.6.2',
    type: 'short-answer',
    bloom: 'evaluate',
    aos: ['AO4'],
    prompt: 'What separates a top-band conclusion from a summary?',
    answer:
      'It answers the question directly, says what the decision depends on, and acknowledges the strongest counter-argument before dismissing it — using evidence from the case, not new points.',
    tags: ['exam-technique', 'high-value'],
    difficulty: 2,
  },
  {
    id: '9609-t-units',
    objectiveId: 's5.5.2',
    type: 'short-answer',
    bloom: 'apply',
    aos: ['AO2'],
    prompt: 'Name three ways calculation marks are commonly thrown away on this paper.',
    answer:
      'Missing units or currency, not showing the method (so no method marks when the answer is wrong), and answering the calculation without then saying what the number means for the business.',
    tags: ['exam-technique', 'calculation'],
    difficulty: 1,
  },
]);

/** Diagnostic MCQs: every wrong option catches a specific, named misconception. */
const diagnostics = authored([
  {
    id: '9609-m-breakeven-fall',
    objectiveId: 's5.5.3',
    type: 'mcq',
    bloom: 'apply',
    aos: ['AO2', 'AO3'],
    prompt:
      'A firm’s fixed costs rise while price and variable cost per unit stay the same. What happens to break-even output?',
    answer: 'It rises, because more units are needed to cover the larger fixed costs.',
    distractors: [
      {
        text: 'It falls, because costs and output move in opposite directions.',
        misconception: 'Treats the break-even formula as inverse without checking which term changed.',
        correction:
          'Break-even = fixed costs ÷ contribution per unit. Fixed costs are on top, so raising them raises break-even output.',
      },
      {
        text: 'It stays the same, because contribution per unit is unchanged.',
        misconception: 'Assumes only contribution drives break-even.',
        correction:
          'Contribution is the denominator; the numerator (fixed costs) changed, so the result changes.',
      },
      {
        text: 'It rises, because contribution per unit falls.',
        misconception: 'Confuses fixed with variable cost — only variable cost changes contribution.',
        correction:
          'Contribution = price − variable cost. A change in fixed costs leaves contribution per unit untouched.',
      },
    ],
    tags: ['break-even', 'diagnostic'],
    difficulty: 1,
  },
  {
    id: '9609-m-liquidity',
    objectiveId: 's10.10.1',
    type: 'mcq',
    bloom: 'analyse',
    aos: ['AO3'],
    prompt:
      'A business has a current ratio of 2.5 and an acid-test ratio of 0.4. What does this most strongly suggest?',
    answer: 'Most of its current assets are inventory, so it could struggle to pay debts quickly.',
    distractors: [
      {
        text: 'It is highly liquid and in a strong short-term position.',
        misconception: 'Reads the current ratio alone and ignores the gap between the two ratios.',
        correction:
          'The gap between the ratios *is* the inventory. A high current ratio with a low acid test is a warning, not reassurance.',
      },
      {
        text: 'It is heavily indebted in the long term.',
        misconception: 'Confuses liquidity ratios with gearing.',
        correction: 'Long-term debt is measured by gearing; these two ratios only describe short-term position.',
      },
      {
        text: 'Its customers are paying too slowly.',
        misconception: 'Confuses slow receivables with high inventory.',
        correction:
          'Receivables are included in the acid test, so slow payers would not open this gap; unsold stock would.',
      },
    ],
    tags: ['ratio', 'diagnostic'],
    difficulty: 1.5,
  },
  {
    id: '9609-m-npv-discount',
    objectiveId: 's10.10.2',
    type: 'mcq',
    bloom: 'analyse',
    aos: ['AO3'],
    prompt: 'A project’s NPV is calculated using a higher discount rate. Everything else is unchanged. What happens?',
    answer: 'NPV falls, because future cash flows are worth less in today’s money.',
    distractors: [
      {
        text: 'NPV rises, because a higher rate means a higher return.',
        misconception: 'Reads the discount rate as the project’s return rather than the cost of waiting.',
        correction:
          'The discount rate is what future money is discounted *by*. Raising it shrinks every future inflow.',
      },
      {
        text: 'NPV is unchanged, because the cash flows have not changed.',
        misconception: 'Forgets that NPV is the discounted, not the raw, sum.',
        correction: 'NPV depends on both the cash flows and the rate they are discounted at.',
      },
      {
        text: 'Only the payback period changes.',
        misconception: 'Confuses payback (undiscounted) with NPV.',
        correction: 'Payback ignores discounting entirely — that is precisely its weakness.',
      },
    ],
    tags: ['investment-appraisal', 'diagnostic'],
    difficulty: 1.5,
  },
  {
    id: '9609-m-motivation',
    objectiveId: 's2.2.2',
    type: 'mcq',
    bloom: 'apply',
    aos: ['AO2', 'AO3'],
    prompt:
      'A manager raises pay to fix low motivation. On Herzberg’s account, what is the most likely outcome?',
    answer: 'Dissatisfaction falls, but motivation does not necessarily rise.',
    distractors: [
      {
        text: 'Motivation rises in proportion to the pay rise.',
        misconception: 'Treats pay as a motivator, which is exactly what Herzberg denies.',
        correction: 'Pay is a hygiene factor: its absence causes dissatisfaction, its presence does not motivate.',
      },
      {
        text: 'Nothing changes at all.',
        misconception: 'Over-corrects — hygiene factors do have a real effect, just not a motivating one.',
        correction: 'Fixing a hygiene factor removes a source of dissatisfaction, which is a genuine gain.',
      },
      {
        text: 'Motivation falls because workers expect more.',
        misconception: 'Imports an unrelated idea about expectations into Herzberg.',
        correction: 'Herzberg predicts neutrality on motivation, not a decline.',
      },
    ],
    tags: ['motivation', 'diagnostic'],
    difficulty: 1,
  },
]);

export const business9609Items: Item[] = [
  ...formulas,
  ...definitions,
  ...frameworks,
  ...technique,
  ...diagnostics,
];
