/**
 * Thousands of generated cases against invariants, rather than a handful of
 * examples somebody thought of.
 *
 * `test-cite.mts` and `test-route.ts` check the cases I could think of. This
 * checks the ones I could not: it generates expressions and compares the
 * calculator against a trusted evaluator, and it lifts quotes verbatim out of
 * generated text to prove the matcher finds them — which is the property that
 * actually matters, and the one a fixed example set can only sample.
 *
 * Both directions are tested, and the second is the important one. A citation
 * matcher that finds everything is useless; the promise is that it finds what
 * is there and refuses what is not.
 *
 * The generator is seeded, so a failure is reproducible rather than a story
 * about something that happened once.
 *
 *   npx jiti test-fuzz.ts
 */
import { solve } from "./lib/arith";
import { extractCitations } from "./lib/cite";

let failed = 0;
const fail = (l: string, d: string) => { failed++; console.log(`  ✗ ${l} — ${d}`); };

// A tiny deterministic PRNG so a failure can be reproduced exactly.
let seed = 12345;
const rnd = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff; };
const pick = <T,>(a: T[]) => a[Math.floor(rnd() * a.length)];
const int = (n: number) => Math.floor(rnd() * n);

console.log("\nArithmetic: generated expressions against a trusted evaluator");
{
  const gen = (depth: number): string => {
    if (depth <= 0 || rnd() < 0.3) return String(int(1000) + 1);
    const op = pick(["+", "-", "*", "/"]);
    const l = gen(depth - 1), r = gen(depth - 1);
    return rnd() < 0.3 ? `(${l} ${op} ${r})` : `${l} ${op} ${r}`;
  };
  let checked = 0, skipped = 0;
  for (let i = 0; i < 4000; i++) {
    const e = gen(3);
    const got = solve(e);
    // The oracle: these are digits and + - * / ( ) only, generated by us.
    let want: number;
    try { want = Function(`"use strict";return (${e})`)() as number; } catch { continue; }
    if (!Number.isFinite(want)) { if (got) fail("non-finite accepted", `${e} → ${got.text}`); continue; }
    if (!got) { skipped++; continue; }
    checked++;
    // Compare on value, not on the printed string: the printer rounds on purpose.
    if (Math.abs(got.value - want) > Math.max(1e-9, Math.abs(want) * 1e-12)) {
      fail("wrong answer", `${e} → ${got.value}, should be ${want}`);
      break;
    }
  }
  console.log(`  ✓ ${checked} generated sums answered correctly (${skipped} declined)`);
}

console.log("\nArithmetic: nothing that is not a sum may be answered");
{
  const words = ["what", "is", "the", "sum", "of", "why", "explain", "binary", "hex", "percent", "apples", "x", "n"];
  let wrong = 0;
  for (let i = 0; i < 3000; i++) {
    const n = 1 + int(5);
    const parts: string[] = [];
    for (let j = 0; j < n; j++) parts.push(rnd() < 0.5 ? pick(words) : String(int(100)));
    const s = parts.join(" ");
    const got = solve(s);
    // If it answered, the input must contain an operator and nothing alphabetic
    // outside the allowed lead-in.
    if (got && /[a-z]/i.test(s.replace(/^\s*(what(?:'s| is)|calculate|compute|how much is)\s*/i, ""))) {
      fail("answered something with words in it", `"${s}" → ${got.text}`);
      if (++wrong > 3) break;
    }
  }
  if (!wrong) console.log("  ✓ 3000 word-bearing inputs, none answered by the calculator");
}

console.log("\nCitations: a quote taken from the source must always be found");
{
  const src = (n: number) => {
    const w = ["the", "market", "grew", "sharply", "in", "spring", "under", "pressure", "from", "rivals",
               "although", "costs", "held", "flat", "which", "nobody", "expected", "given", "the", "quarter"];
    const out: string[] = [];
    for (let i = 0; i < n; i++) out.push(pick(w));
    return out.join(" ");
  };
  let ok = 0, bad = 0;
  for (let i = 0; i < 1500; i++) {
    const text = src(120);
    const words = text.split(" ");
    const at = int(words.length - 12);
    const quote = words.slice(at, at + 6 + int(6)).join(" ");
    const source = { id: "s", noteId: "n", name: "f.md", text, size: 0, addedAt: 0 } as never;
    const out = extractCitations(`X [[cite: f.md | ${quote}]]`, [source]);
    if (!out.citations[0]?.found) {
      fail("a quote lifted verbatim from the source was not found", JSON.stringify(quote));
      if (++bad > 2) break;
    } else {
      ok++;
      const { start, end } = out.citations[0].at!;
      const got = text.slice(start, end).toLowerCase().replace(/\s+/g, " ").trim();
      if (got !== quote.toLowerCase().replace(/\s+/g, " ").trim()) {
        fail("the offsets do not point at the quoted words", `got "${got}" for "${quote}"`);
        if (++bad > 2) break;
      }
    }
  }
  if (!bad) console.log(`  ✓ ${ok} verbatim quotes found, and every offset pointed at the right words`);
}

console.log("\nCitations: words that are not in the source must never be found");
{
  let bad = 0, ok = 0;
  for (let i = 0; i < 1500; i++) {
    const text = "alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu nu xi omicron pi";
    const fake = ["rho sigma tau upsilon phi chi", "the market grew by forty percent", "nobody said that at all",
                  "zzzz yyyy xxxx wwww vvvv uuuu"][int(4)];
    const source = { id: "s", noteId: "n", name: "f.md", text, size: 0, addedAt: 0 } as never;
    const out = extractCitations(`X [[cite: f.md | ${fake}]]`, [source]);
    if (out.citations[0]?.found) { fail("found words that are not in the source", fake); if (++bad > 2) break; }
    else ok++;
  }
  if (!bad) console.log(`  ✓ ${ok} invented quotes, none of them matched`);
}

console.log("\nCitations: markers and the stored list must stay in step");
{
  let bad = 0;
  for (let i = 0; i < 600; i++) {
    const n = 1 + int(6);
    const text = "alpha beta gamma delta epsilon zeta eta theta iota kappa";
    const source = { id: "s", noteId: "n", name: "f.md", text, size: 0, addedAt: 0 } as never;
    let raw = "";
    for (let j = 0; j < n; j++) {
      raw += rnd() < 0.5
        ? `sentence ${j} [[cite: f.md | alpha beta gamma delta]] `
        : `sentence ${j} [[cite: f.md | not in here at all friend]] `;
    }
    const out = extractCitations(raw, [source]);
    if (out.citations.length !== n) { fail("citation count does not match what was emitted", `${out.citations.length} vs ${n}`); if (++bad > 2) break; continue; }
    for (const c of out.citations) {
      const marker = c.found ? `[${c.n}](#armi-cite-${c.n})` : `[${c.n}?](#armi-cite-${c.n})`;
      if (!out.text.includes(marker)) { fail("a citation has no marker in the text", marker); if (++bad > 2) break; }
    }
    if (/\[\[cite:/.test(out.text)) { fail("raw citation syntax left on the page", out.text.slice(0, 60)); if (++bad > 2) break; }
  }
  if (!bad) console.log("  ✓ 600 mixed pages, every citation numbered and marked, no syntax left behind");
}

console.log(failed ? `\n  ${failed} failed` : "\n  all passed");
process.exit(failed ? 1 : 0);
