/**
 * Thousands of generated cases against invariants, rather than a handful of
 * examples somebody thought of.
 *
 * `test-cite.mts` and `test-route.ts` check the cases I could think of. This
 * checks the ones I could not: it generates expressions and compares the
 * calculator against a trusted evaluator, and it lifts quotes verbatim out of
 * generated text to prove the matcher finds them — which is the property that
 * actually matters, and the one a fixed example set can only sample.
 *
 * Both directions are tested, and the second is the important one. A citation
 * matcher that finds everything is useless; the promise is that it finds what
 * is there and refuses what is not.
 *
 * The generator is seeded, so a failure is reproducible rather than a story
 * about something that happened once.
 *
 *   npx jiti test-fuzz.ts
 */
import { solve } from "./lib/arith";
import { extractCitations, findIn, normalise } from "./lib/cite";

let failed = 0;
const fail = (l: string, d: string) => { failed++; console.log(`  ✗ ${l} — ${d}`); };

// A tiny deterministic PRNG so a failure can be reproduced exactly.
let seed = 12345;
const rnd = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff; };
const pick = <T,>(a: T[]) => a[Math.floor(rnd() * a.length)];
const int = (n: number) => Math.floor(rnd() * n);

console.log("\nArithmetic: generated expressions against a trusted evaluator");
{
  const gen = (depth: number): string => {
    if (depth <= 0 || rnd() < 0.3) return String(int(1000) + 1);
    const op = pick(["+", "-", "*", "/"]);
    const l = gen(depth - 1), r = gen(depth - 1);
    return rnd() < 0.3 ? `(${l} ${op} ${r})` : `${l} ${op} ${r}`;
  };
  let checked = 0, skipped = 0;
  for (let i = 0; i < 4000; i++) {
    const e = gen(3);
    const got = solve(e);
    // The oracle: these are digits and + - * / ( ) only, generated by us.
    let want: number;
    try { want = Function(`"use strict";return (${e})`)() as number; } catch { continue; }
    if (!Number.isFinite(want)) { if (got) fail("non-finite accepted", `${e} → ${got.text}`); continue; }
    if (!got) { skipped++; continue; }
    checked++;
    // Compare on value, not on the printed string: the printer rounds on purpose.
    if (Math.abs(got.value - want) > Math.max(1e-9, Math.abs(want) * 1e-12)) {
      fail("wrong answer", `${e} → ${got.value}, should be ${want}`);
      break;
    }
  }
  console.log(`  ✓ ${checked} generated sums answered correctly (${skipped} declined)`);
}

console.log("\nArithmetic: an integer answer is the integer, to the last digit");
{
  /* The float oracle above compares within a tolerance, which is the right
     comparison for a quotient and exactly the wrong one for a product: the bug
     that made this file worth rewriting was `123456789 * 987654321` coming back
     nine short, and a 1e-12 tolerance waves that through. So integers are
     checked against BigInt, digit for digit, with no tolerance at all. */
  const gen = (depth: number): string => {
    if (depth <= 0 || rnd() < 0.35) return String(int(1_000_000_000) + 1);
    const op = pick(["+", "-", "*"]);
    const l = gen(depth - 1), r = gen(depth - 1);
    return rnd() < 0.3 ? `(${l} ${op} ${r})` : `${l} ${op} ${r}`;
  };
  let checked = 0;
  for (let i = 0; i < 2000; i++) {
    const e = gen(3);
    const got = solve(e);
    if (!got) continue;
    // The oracle: the same expression in BigInt, which cannot round.
    const want = Function(`"use strict";return (${e.replace(/(\d+)/g, "$1n")})`)() as bigint;
    const neg = want < 0n;
    const digits = (neg ? -want : want).toString();
    const grouped = (neg ? "-" : "") + digits.replace(/\B(?=(\d{3})+$)/g, ",");
    checked++;
    if (got.text !== grouped) {
      fail("not exact", `${e} → ${got.text}, should be ${grouped}`);
      break;
    }
  }
  console.log(`  ✓ ${checked} integer sums exact to the last digit, BigInt against BigInt`);
}

console.log("\nArithmetic: the shapes that are also dates are never answered");
{
  let wrong = 0;
  for (let i = 0; i < 2000; i++) {
    const a = int(9999) + 1, b = int(9999) + 1, c = int(9999) + 1;
    const sep = pick(["/", "-"]);
    const body = rnd() < 0.5 ? `${a}${sep}${b}` : `${a}${sep}${b}${sep}${c}`;
    const asked = pick(["", "what is ", "calculate ", "how much is "]) + body;
    const got = solve(asked);
    if (got) {
      fail("answered a date, a phone number or an idiom", `"${asked}" → ${got.text}`);
      if (++wrong > 3) break;
    }
  }
  if (!wrong) console.log("  ✓ 2000 date- and phone-shaped inputs, none of them answered as arithmetic");
}

console.log("\nArithmetic: nothing that is not a sum may be answered");
{
  const words = ["what", "is", "the", "sum", "of", "why", "explain", "binary", "hex", "percent", "apples", "x", "n"];
  let wrong = 0;
  for (let i = 0; i < 3000; i++) {
    const n = 1 + int(5);
    const parts: string[] = [];
    for (let j = 0; j < n; j++) parts.push(rnd() < 0.5 ? pick(words) : String(int(100)));
    const s = parts.join(" ");
    const got = solve(s);
    // If it answered, the input must contain an operator and nothing alphabetic
    // outside the allowed lead-in.
    if (got && /[a-z]/i.test(s.replace(/^\s*(what(?:'s| is)|calculate|compute|how much is)\s*/i, ""))) {
      fail("answered something with words in it", `"${s}" → ${got.text}`);
      if (++wrong > 3) break;
    }
  }
  if (!wrong) console.log("  ✓ 3000 word-bearing inputs, none answered by the calculator");
}

console.log("\nCitations: folding is idempotent and never loses its place");
{
  /* The map and the folded text must stay the same length, which is the
     invariant every offset in a citation depends on. It broke on `İ`, whose
     lowercase is two characters, and the symptom was a citation that opened on
     the whole document rather than on the sentence. Fed here on purpose, along
     with everything else the folder touches. */
  const chars = ["a", "b", " ", "  ", "\n", "\r\n", "-", "--", "\u2014", "\u2013", "\u2018", "\u2019", "\u201c", "\u201d",
                 "\u0130", "\u0131", "\u00df", "A", "Z", "\u00c9", "\u03a3", "7", "\t"];
  let bad = 0;
  for (let i = 0; i < 3000; i++) {
    let s = "";
    for (let j = 0, n = 1 + int(40); j < n; j++) s += pick(chars);
    const once = normalise(s);
    if (normalise(once) !== once) {
      fail("folding is not idempotent", `${JSON.stringify(s)} → ${JSON.stringify(once)} → ${JSON.stringify(normalise(once))}`);
      if (++bad > 3) break;
    }
    /* And the map has to still point somewhere sensible: a needle taken out of
       the folded text must come back as a span of the original. */
    if (once.length >= 12) {
      const at = int(Math.max(1, once.length - 12));
      const want = once.slice(at, at + 12);
      const hit = findIn(s, want);
      if (!hit || hit.start < 0 || hit.end > s.length || hit.end <= hit.start) {
        fail("a fragment of the folded text did not map back", `${JSON.stringify(s)} / ${JSON.stringify(want)} → ${JSON.stringify(hit)}`);
        if (++bad > 3) break;
      }
    }
  }
  if (!bad) console.log("  ✓ 3000 folded strings, idempotent and every offset inside the original");
}

console.log("\nCitations: a quote taken from the source must always be found");
{
  const src = (n: number) => {
    const w = ["the", "market", "grew", "sharply", "in", "spring", "under", "pressure", "from", "rivals",
               "although", "costs", "held", "flat", "which", "nobody", "expected", "given", "the", "quarter"];
    const out: string[] = [];
    for (let i = 0; i < n; i++) out.push(pick(w));
    return out.join(" ");
  };
  let ok = 0, bad = 0;
  for (let i = 0; i < 1500; i++) {
    const text = src(120);
    const words = text.split(" ");
    const at = int(words.length - 12);
    const quote = words.slice(at, at + 6 + int(6)).join(" ");
    const source = { id: "s", noteId: "n", name: "f.md", text, size: 0, addedAt: 0 } as never;
    const out = extractCitations(`X [[cite: f.md | ${quote}]]`, [source]);
    if (!out.citations[0]?.found) {
      fail("a quote lifted verbatim from the source was not found", JSON.stringify(quote));
      if (++bad > 2) break;
    } else {
      ok++;
      const { start, end } = out.citations[0].at!;
      const got = text.slice(start, end).toLowerCase().replace(/\s+/g, " ").trim();
      if (got !== quote.toLowerCase().replace(/\s+/g, " ").trim()) {
        fail("the offsets do not point at the quoted words", `got "${got}" for "${quote}"`);
        if (++bad > 2) break;
      }
    }
  }
  if (!bad) console.log(`  ✓ ${ok} verbatim quotes found, and every offset pointed at the right words`);
}

console.log("\nCitations: words that are not in the source must never be found");
{
  let bad = 0, ok = 0;
  for (let i = 0; i < 1500; i++) {
    const text = "alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu nu xi omicron pi";
    const fake = ["rho sigma tau upsilon phi chi", "the market grew by forty percent", "nobody said that at all",
                  "zzzz yyyy xxxx wwww vvvv uuuu"][int(4)];
    const source = { id: "s", noteId: "n", name: "f.md", text, size: 0, addedAt: 0 } as never;
    const out = extractCitations(`X [[cite: f.md | ${fake}]]`, [source]);
    if (out.citations[0]?.found) { fail("found words that are not in the source", fake); if (++bad > 2) break; }
    else ok++;
  }
  if (!bad) console.log(`  ✓ ${ok} invented quotes, none of them matched`);
}

console.log("\nCitations: markers and the stored list must stay in step");
{
  let bad = 0;
  for (let i = 0; i < 600; i++) {
    const n = 1 + int(6);
    const text = "alpha beta gamma delta epsilon zeta eta theta iota kappa";
    const source = { id: "s", noteId: "n", name: "f.md", text, size: 0, addedAt: 0 } as never;
    let raw = "";
    for (let j = 0; j < n; j++) {
      raw += rnd() < 0.5
        ? `sentence ${j} [[cite: f.md | alpha beta gamma delta]] `
        : `sentence ${j} [[cite: f.md | not in here at all friend]] `;
    }
    const out = extractCitations(raw, [source]);
    if (out.citations.length !== n) { fail("citation count does not match what was emitted", `${out.citations.length} vs ${n}`); if (++bad > 2) break; continue; }
    for (const c of out.citations) {
      const marker = c.found ? `[${c.n}](#armi-cite-${c.n})` : `[${c.n}?](#armi-cite-${c.n})`;
      if (!out.text.includes(marker)) { fail("a citation has no marker in the text", marker); if (++bad > 2) break; }
    }
    if (/\[\[cite:/.test(out.text)) { fail("raw citation syntax left on the page", out.text.slice(0, 60)); if (++bad > 2) break; }
  }
  if (!bad) console.log("  ✓ 600 mixed pages, every citation numbered and marked, no syntax left behind");
}

console.log(failed ? `\n  ${failed} failed` : "\n  all passed");
process.exit(failed ? 1 : 0);
