/**
 * Content schemas.
 *
 * Every piece of study content — however it arrived, whether typed by a learner,
 * parsed from a PDF, or generated by a model — is validated through these schemas
 * before it is stored. Two fields are load-bearing and must never be optional:
 *
 *  - `provenance`: where this content came from. Ungrounded model output is
 *    labelled as such, forever (MASTER-PROMPT.md §1.2).
 *  - `licence`: what we are allowed to do with it. Retrofitting this is impossible,
 *    so it exists from the first migration (§7).
 */

import { z } from 'zod';

/** Assessment objectives. Cambridge's four; other boards map onto the same shape. */
export const AssessmentObjective = z.enum(['AO1', 'AO2', 'AO3', 'AO4']);
export type AssessmentObjective = z.infer<typeof AssessmentObjective>;

export const AO_LABELS: Record<AssessmentObjective, string> = {
  AO1: 'Knowledge & understanding',
  AO2: 'Application',
  AO3: 'Analysis',
  AO4: 'Evaluation',
};

/** Bloom level — drives how an item is generated, marked, and spaced. */
export const BloomLevel = z.enum([
  'remember',
  'understand',
  'apply',
  'analyse',
  'evaluate',
  'create',
]);
export type BloomLevel = z.infer<typeof BloomLevel>;

/** Where a piece of content came from. Never inferred, always recorded. */
export const Provenance = z.enum([
  /** Written by a human author for this app. */
  'authored',
  /** Extracted from a document the learner uploaded. */
  'user-upload',
  /** Ingested from an openly licensed source. */
  'open-source-material',
  /** Generated by a model and grounded in a cited source. */
  'model-grounded',
  /** Generated by a model from its own knowledge. Must be shown as unverified. */
  'model-unverified',
]);
export type Provenance = z.infer<typeof Provenance>;

export const Licence = z.enum([
  'authored-atlas',
  'CC0',
  'CC-BY',
  'CC-BY-SA',
  'public-domain',
  /** Learner's own file. Private to them; never pooled, never used for training. */
  'user-private',
  'unknown',
]);
export type Licence = z.infer<typeof Licence>;

export const ItemType = z.enum([
  'definition',
  'formula',
  'cloze',
  'mcq',
  'short-answer',
  'numeric',
  'application',
  'evaluation',
  'essay',
  'data-response',
]);
export type ItemType = z.infer<typeof ItemType>;

/** A distractor must name the misconception it detects — never a random wrong answer. */
export const Distractor = z.object({
  text: z.string().min(1),
  /** The named misconception this option catches. */
  misconception: z.string().min(1),
  /** Shown when the learner picks it: the targeted correction. */
  correction: z.string().min(1),
});
export type Distractor = z.infer<typeof Distractor>;

export const Item = z.object({
  id: z.string().min(1),
  /** Syllabus node this item assesses. */
  objectiveId: z.string().min(1),
  type: ItemType,
  bloom: BloomLevel,
  /** Which assessment objectives this item exercises. */
  aos: z.array(AssessmentObjective).min(1),
  prompt: z.string().min(1),
  answer: z.string().min(1),
  /** Optional worked reasoning, shown after the answer, never before. */
  working: z.string().optional(),
  distractors: z.array(Distractor).optional(),
  /** Latent difficulty, -4..+4 on the mastery scale. 0 = average. */
  difficulty: z.number().min(-4).max(4).default(0),
  /** Acceptable numeric tolerance, for numeric items. */
  tolerance: z.number().nonnegative().optional(),
  unit: z.string().optional(),
  provenance: Provenance,
  licence: Licence,
  /** Free-form tags: formula, framework, command-word, trap, etc. */
  tags: z.array(z.string()).default([]),
});
export type Item = z.infer<typeof Item>;

/** A node in the syllabus tree. Leaves carry the objectives that items attach to. */
export const SyllabusNode = z.object({
  id: z.string().min(1),
  /** Board's own numbering, e.g. "3.2". */
  code: z.string().optional(),
  title: z.string().min(1),
  /** Parent node id, null for a top-level section. */
  parentId: z.string().nullable(),
  /** Which qualification level this node belongs to. */
  level: z.enum(['AS', 'A2', 'both']),
  /** Relative teaching weight inside its parent, used to spread marks. */
  weight: z.number().positive().default(1),
});
export type SyllabusNode = z.infer<typeof SyllabusNode>;

export const Paper = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  /** Raw marks available on the paper. */
  rawMarks: z.number().positive(),
  /** Share of the full qualification, 0..1. */
  qualificationWeight: z.number().min(0).max(1),
  durationMinutes: z.number().positive(),
  /** Share of this paper's marks per assessment objective; must sum to 1. */
  aoWeights: z.record(AssessmentObjective, z.number().min(0).max(1)),
  /** Which syllabus level the paper draws on. */
  level: z.enum(['AS', 'A2']),
});
export type Paper = z.infer<typeof Paper>;

export const Syllabus = z.object({
  id: z.string().min(1),
  board: z.string().min(1),
  subject: z.string().min(1),
  /** Board's syllabus code, e.g. "9609". */
  code: z.string().min(1),
  /** Years this syllabus version is live for. */
  validFor: z.string().min(1),
  papers: z.array(Paper).min(1),
  nodes: z.array(SyllabusNode).min(1),
  /** Human-readable note on where the structure came from. */
  sourceNote: z.string(),
});
export type Syllabus = z.infer<typeof Syllabus>;

/** Validate a syllabus and fail loudly — a silently malformed syllabus corrupts every plan built on it. */
export function parseSyllabus(input: unknown): Syllabus {
  const syllabus = Syllabus.parse(input);
  for (const paper of syllabus.papers) {
    const total = Object.values(paper.aoWeights).reduce((s, w) => s + (w ?? 0), 0);
    if (Math.abs(total - 1) > 0.001) {
      throw new Error(`Paper ${paper.id}: AO weights sum to ${total.toFixed(3)}, expected 1`);
    }
  }
  const ids = new Set(syllabus.nodes.map((n) => n.id));
  for (const node of syllabus.nodes) {
    if (node.parentId !== null && !ids.has(node.parentId)) {
      throw new Error(`Syllabus node ${node.id} has unknown parent ${node.parentId}`);
    }
  }
  return syllabus;
}

export function parseItems(input: unknown): Item[] {
  return z.array(Item).parse(input);
}
